name: Java CI

on:
  repository_dispatch:
    types: run-tests
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        run: mvn "-Dtest=*APITest" test
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Functional Tests
          text: Functional Tests
          only_mention_fail: USXBM5WPQ
          channel: '@shridhk'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required



#curl -H "Accept: application/vnd.github.everest-preview+json" \
#  -H "Authorization: token <TOKEN>" \
#  --request POST \
#  --data '{"event_type": "run-tests"}' \
#  https://api.github.com/repos/ProjectEKA/ProjectEKATests/dispatches