name: Manual workflow on Dev

on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
      - refactor-mobile-tests

jobs:
  mobile-test-nhs-dev:
    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up node
        uses: actions/setup-node@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          fetch-depth: 1
          node-version: '10.16'
          java-version: 11
      - run: npm install -g appium
      - name: run mobile tests on NHS Dev
        uses: reactivecircus/android-emulator-runner@v2
        with:
          arch: x86
          api-level: 27
          target: google_apis
          profile: pixel_2
          script: avdmanager list && mvn clean "-Dtest=/**/mobiletests/tests/LoginTest" test
        env:
          Authorization: ${{ secrets.Authorization }}
          env: nhsDev # required
      - name: Notify on Slack
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Functional Tests on NHS Dev
          text: Functional Mobile Tests on NHS Dev
          channel: '#botcave'
          only_mention_fail: USXBM5WPQ,here
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always()

#curl -H "Accept: application/vnd.github.everest-preview+json" \
#  -H "Authorization: token <TOKEN>" \
#  --request POST \
#  --data '{"event_type": "run-tests"}' \
#  https://api.github.com/repos/ProjectEKA/ProjectEKATests/dispatches