# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
      mobile-test-nhs-UAT:
        runs-on: macOS-latest
        steps:
          - name: checkout
            uses: actions/checkout@v2
          - name: set up node
            uses: actions/setup-node@v1
          - name: Set up JDK 1.8
            uses: actions/setup-java@v1
            with:
              fetch-depth: 1
              node-version: '10.16'
              java-version: 1.8
          - run: npm install -g appium
          - name: run mobile tests on NHS Dev
            uses: reactivecircus/android-emulator-runner@v2
            with:
              api-level: 29
              profile: Nexus 6
              script: mvn clean "-Dtest=/**/MobileAppTests/Tests/LoginTest" test
            env:
              Authorization: ${{ secrets.Authorization }}
              env: nhsUAT # required
          - name: Notify on Slack
            uses: 8398a7/action-slack@v2
            with:
              status: ${{ job.status }}
              author_name: Functional Tests on NHS UAT
              text: Functional Mobile Tests on NHS UAT
              channel: '#botcave'
              only_mention_fail: USXBM5WPQ,here
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
              SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
            if: always()
